[DEFAULT]
VoiceUrl = http://192.168.1.1:8124/synthesize/
VolumeLevel = 75

[LOCALSPEAK]
# Collection of txt file phrases for pre generated snark
greetings = greetings.txt
processing = processing.txt
insults = insults.txt
questions = questions.txt
qresponses = question_response.txt
fuck = fuck.txt

[OPENAI]
# open ai connections for chatgpt
endpoint = https://api.openai.com/v1/chat/completions
apikey = REDACTED
#model = gpt-4
model = gpt-3.5-turbo
