[DEFAULT]
VoiceUrl = http://192.168.1.1:8124/synthesize/
VolumeLevel = 75
ZMQListenAddress = 192.168.1.1
ZMQListenPort = 5555
ZMQSenderAddress = 192.168.1.2
ZMQSenderPort = 5555
working_root = ./glados-home
aperture_animation = ./aperture_logo

[CAMERAS]
Camera_Head_Factory = Camera_Head
Camera_Head = 0
Camera_Head_Picam = True
Camera_Head_Resolution = 640,480
Camera_Head_FPS = 4
Camera_Left_Factory = Camera_Left
Camera_Left = 1
Camera_Left_Picam = True
Camera_Left_Resolution = 640,480
Camera_Left_FPS = 4
Camera_Right_Factory = Camera_Right
Camera_Right = 0
Camera_Right_Picam = True
Camera_Right_Resolution = 640,480
Camera_Right_FPS = 4

[SERVOS]
default_max_min = 180,0
mg90d_pulse = 2665, 610
mg90d_speed = 0.1
mg92b_pulse = 2550, 605
mg92b_speed = 0.12
head_min_max = 173,6

[RTSP]
rtsp_port = 8554
rtsp_server_ip = 192.168.1.1

[MQTT]
mqtt_port = 1883
mqtt_server_ip = 192.168.1.2

[YOLO]
model = yolov8m.pt

[HOMEASSISTANT]
token = REDACTED
api = http://192.168.1.1:8123/api
weather_entity = weather.forecast_home

[LOCALSPEAK]
# Collection of txt file phrases for pre generated snark
localpath = ./txt_responses
greetings = greetings.txt
processing = processing.txt
insults = insults.txt
questions = questions.txt
qresponses = question_response.txt
fuck = fuck.txt
cancel = cancel_response.txt
VisionConfidence = 0.65

[OPENAI]
# open ai connections for chatgpt
endpoint = https://api.openai.com/v1/chat/completions
apikey = REDACTED
#model = gpt-4
model = gpt-3.5-turbo