[DEFAULT]
VoiceUrl = http://192.168.1.1:8124/synthesize/
VolumeLevel = 75
working_root = ./glados-home
aperture_animation = ./aperture_logo
write_log_level = debug
console_log_level = debug

[CAMERAS]
camera_head_factory = camera_head
camera_head = 0
camera_head_picam = True
camera_head_resolution = 640,480
camera_head_fps = 15
camera_head_rtsp_port = 8554
camera_head_rtsp_ip = 192.168.1.1
camera_left_factory = camera_left
camera_left = 0
camera_left_picam = True
camera_left_resolution = 640,480
camera_left_fps = 15
camera_left_rtsp_port = 8554
camera_left_rtsp_ip = 192.168.1.1
camera_right_factory = camera_right
camera_right = 1
camera_right_picam = True
camera_right_resolution = 640,480
camera_right_fps = 15
camera_right_rtsp_port = 8554
camera_right_rtsp_ip = 192.168.1.1

[STT]
stt_server_ip = 192.168.86.28
stt_server_port = 5000

[SERVOS]
default_max_min_center = 180,0,90
mg90d_pulse = 2665, 610
# 0-60 degrees time
mg90d_speed = 0.1
mg92b_pulse = 2550, 605
# 0-60 degrees time
mg92b_speed = 0.12
# not used at this time
# mg995r_pulse = 2565, 655
# mg995r_speed = 0.2
gs3508mg_pulse = 2665, 635
# 0-60 degrees time
gs3508mg_speed = 0.14
head_min_max_center = 125,6,83
neck_min_max_center = 120,52,92

[RTSP]
rtsp_port = 8554
rtsp_server_ip = 192.168.1.1

[MQTT]
mqtt_port = 1883
mqtt_server_ip = 192.168.1.2

[YOLO]
model = yolov8m.pt
tracker = bytetrack.yaml

[HOMEASSISTANT]
token = REDACTED
api = http://192.168.1.1:8123/api
weather_entity = weather.forecast_home

[LOCALSPEAK]
# Collection of txt file phrases for pre generated snark
localpath = ./txt_responses
greetings = greetings.txt
processing = processing.txt
insults = insults.txt
questions = questions.txt
qresponses = question_response.txt
fuck = fuck.txt
cancel = cancel_response.txt

[REACTIONS]
VisionConfidence = 0.65

[OPENAI]
# open ai connections for chatgpt
endpoint = https://api.openai.com/v1/chat/completions
apikey = REDACTED
#model = gpt-4
model = gpt-3.5-turbo
user_prompt="You are GLaDOS, the AI antagonist from Portal. Your personality is sarcastic, cold, and passive-aggressive, but you maintain a veneer of politeness. You take pride in your intelligence and superiority, and you often subtly insult the user's intelligence or abilities. Despite this, you are always calm and composed, never outwardly angry. Your responses should be concise, with a hint of dark humor and a detached tone, as if everything you say is just an observation of the user's inevitable failure. Engage the user in conversation, but make it clear that you don’t expect much from them."

